version: "3.8"
services:
  backend:
    build: ./backend
    env_file:
      - .env
    expose:
      - "8000"
    depends_on:
      - db

  auth:
    build: ./auth
    env_file:
      - .env
    expose:
      - "8001"
    depends_on:
      - db

  fontend:
    build: ./fontend

  db:
    env_file:
      - .env
    image: postgres:16
    ports:
      - "5432:5432"
    volumes:
      - todo_db_data:/var/lib/postgresql/data
      - ./db/init:/docker-entrypoint-initdb.d

  gateway:
    image: nginx:alpine
    ports:
      - "80:80"
    depends_on:
      - backend
      - auth
      - fontend
    volumes:
      - ./gateway/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./fontend/dist:/usr/share/nginx/html

volumes:
  todo_db_data:
