version: "3.8"
services:
  backend:
    build: ./backend
    env_file:
      - ./.env
    ports:
      - "8000:8000"
    depends_on:
      - db

  auth:
    build: ./auth
    env_file:
      - ./.env
    ports:
      - "8001:8001"
    depends_on:
      - db

  fontend:
    build: ./fontend

  gateway:
    image: nginx:alpine
    container_name: gateway
    ports:
      - "80:80"
    volumes:
      - ./gateway/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./fontend/dist:/usr/share/nginx/html:ro
    depends_on:
      - backend
      - auth
      - fontend

  db:
    env_file:
      - ./.env
    image: postgres:16
    ports:
      - "5432:5432"
    volumes:
      - todo_db_data:/var/lib/postgresql/data
      - ./db/init:/docker-entrypoint-initdb.d

volumes:
  todo_db_data:
